device:
- name: "Chameleon RevE-Rebooted"
  vendor: "03eb"
  product: "2044"
  cdc: "Atmel Corporation LUFA CDC"
  config:
    slot:
      selected: 4
      offset: 0
      first: 0
      last: 7
    serial:
      baud: 115200
      waitforreceive: 100
      connectiontimeout: 5
      autoconnect: false
  cmdset: # RevE-Rebooted
    version: VERSIONMY
    config: CONFIGMY
    uid: UIDMY
    upload: UPLOADMY
    download: DOWNLOADMY
    reset: RESETMY
    upgrade: UPGRADEMY
    memory: MEMSIZEMY
    uidsize: UIDSIZEMY
    button: BUTTONMY
    buttonl: BUTTON_LONGMY
    setting: SETTINGMY
    clear: CLEARMY
    help: HELPMY
    rssi: RSSIMY
- name: "Chameleon RevG"
  vendor: "16d0"
  product: "04b2"
  cdc: "KAOS Chameleon-Mini"
  config:
    slot:
      selected: 7
      offset: 1
      first: 1
      last: 8
    serial:
      baud: 115200
      waitforreceive: 50
      connectiontimeout: 10
      autoconnect: false
  cmdset:
    version: VERSION
    config: CONFIG
    uid: UID
    readonly: READONLY
    upload: UPLOAD
    download: DOWNLOAD
    reset: RESET
    upgrade: UPGRADE
    memory: MEMSIZE
    uidsize: UIDSIZE
    button: RBUTTON
    buttonl: RBUTTON_LONG
    rbutton: RBUTTON
    rbuttonl: RBUTTON_LONG
    lbutton: LBUTTON
    lbuttonl: LBUTTON_LONG
    setting: SETTING
    clear: CLEAR
    help: HELP
    rssi: RSSI
    ledgreen: LEDGREEN
    ledred: LEDRED
    logmode: LOGMODE
    logmem: LOGMEM
    logdownload: LOGDOWNLOAD
    logstore: LOGSTORE
    logclear: LOGCLEAR
    store: STORE
    recall: RECALL
    charging: CHARGING
    systick: SYSTICK
    sendraw: SEND_RAW
    send: SED
    getuid: GETUID
    dumpmfu: DUMP_MFU
    identify: IDENTIFY
    timeout: TIMEOUT
    threshold: THRESHOLD
    autocalibrate: AUTOCALIBRATE
    field: FIELD
gui:
  title: "Chameleon Gui2"